### ISSUE TITLE
Maya: Parse texture colorspace and naming on Look Publish

### ISSUE THREAD

**Issue by lucanvisuals** [ynput/OpenPype#4713]
# Parsing texture colorspace and naming on Look Publish

We have to transform the texture colorspace to the rendering space on publishing along with the tx file conversion.
When assigning a look in production, all tx files should be set to Raw colorspace and color should be fine. 

Instead of using the source texture file names, it would be helpful for archiving if we could have a consistent naming convention for the published tx textures. This could be something like... `{assetname}_tex_{texture_channel}_{version}_{udim}.tx`

## **Describe the solution you'd like**
Published Texture naming could be comprised of the context asset name, the parsed channel and udim from the source name. 
It could also make some color transform deductions based on the source channel name (which would be parsed into a consistent studio convention).

## **Describe alternatives you've considered**
In the past, we have used a cmd script to parse textures before we started shading, this had it's workflow challenges, but I think there is something to be looked into here. We've used a lookup dictionary to detect and set a consistet channel schema and also make some assumptions about the types of channel ie. whether it was scalar data or color information. This automated the colorspace assignment process upon loading the texture into maya. 

There's an extensive list here, https://github.com/aydinyanik/clarisse_survival_kit/blob/c32f48b0f2a6e1e5611109a19e9dbae03b4c563a/clarisse_survival_kit/settings.py#L8-L24

### However, here's my dictionary:
```python
# tex_library.py 
# Libraries of different parameters for texture processing
# Last Updated: 2019_10_30

KNOWNCHANNELS = {
				# Shading
				('BC', 'basecol', 'basecolour', 'BaseColor', 'base'):	'basecolor',
				('C','dif', 'diff', 'col', 'TEX', 'color'):	'diffuse',
				('A') : 'albedo',
				('RFL', 'reflection') : 'reflect',
				('S', 'specular') : 'spec',
				('M', 'metallic'):	'metal',
				('R', 'roughness', 'rgh'):	'rough',
				('G', 'glossiness') : 'gloss', 
				('I', 'ior') : 'ior',
				('RFR', 'refraction') : 'refract',
				('B') : 'bump',
				('N', 'normal', 'norm', 'nrm', 'nor'): 'tnorm',
				('D', 'displacement', 'displace') : 'disp',
				('T', 'transparancy', 'trans', 'transp') : 'transp',
				('VD', 'vector_disp', 'vdm' ,'vector_displace', 'vector_displacement') : 'vdisp',
				('H') : 'height',
				('SSS', 'subsurface') : 'ssscol',
				('SSW', 'subsurface_weight') : 'sssweight',
				('OP') : 'opacity',
				('EM', 'emissive', 'emit', 'emission') : 'selfillum',
				('ANIW', 'anisotropy_weight') : 'anisot',
				('ANIR', 'anisotropy_rotaion') : 'anisang',
				# Utilities
				('WN', 'world_space_normals') : 'wsnorm',
				('P', 'position'): 'pos',
				('CA', 'cav') : 'cavity',
				('CU', 'curvature') : 'curve',
				('AO', 'ambient_occlusion', 'occ', 'oc') : 'ao',
				('THK', 'thickness') : 'thick',
				('RGB', 'alpha', 'matte', 'mask') : 'rgb_matte',
				('ID') :'id'
				}

KNOWNCOLORSPACES = {
				('srgb'): 'srgb_texture',
				('outs'): 'out_srgb',
				('outr'): 'out_rec709',
				('lin', 'linear'): 'lin_srgb',
				('raw'): 'raw',
				('acescg', 'cg'): 'acescg',
				('acescc', 'cc'): 'acescc'
				}

KNOWNSRGBCHANNELS = ('basecolor', 'diffuse', 'albedo', 'reflect', 'refract', 'ssscol', 'selfillum', 'transp')

KNOWNEXTENSIONS = ("tiff", "tif", "TIFF",
					"exr", "EXR",
					"png", "PNG",
					"bmp", "BMP",
					"jpg", "JPG", "jpeg",
					)
```

### This was the implementation at the time through cmd with OCIO and maketx:
```python
# eg
# maketx -v -u --oiio --checknan --filter lanczos3 P:\Production\01_projects\rnd\python_image\pirate_hat_tex_v02.tif -o P:\Production\01_projects\rnd\python_image\pirate_hat_tex_v02_maketx.tif
import os
import subprocess
import argparse

# in same directory
from tex_library import *

PARMS = r"-v -u -d half --tile 64 64 --separate --checknan --constant-color-detect --monochrome-detect"
COLORCONFIG = os.environ["OCIO"]

SOURCEDIR = os.getcwd()

parser = argparse.ArgumentParser(description='Tiled EXR Texture Converter [srgb_texture -> acescg]')
parser.add_argument('-o', '--out_dir', type=str, metavar='', required=False, help='The optional output directory (has to exist)')
parser.add_argument('-lin', '--linear_mode', required=False, action='store_true', help='linear_srgb conversion mode [lin_srgb -> acescg]')
parser.add_argument('-srgb', '--out_srgb', required=False, action='store_true', help='legacy_srgb conversion mode [out_srgb -> acescg]')
parser.add_argument('-r', '--raw', required=False, action='store_true', help='no color transforms [raw -> raw]')

group = parser.add_mutually_exclusive_group()
# group.add_argument()
group.add_argument('-a', '--asset_name', type=str, help='asset name for texture name')
group.add_argument('-hdri', '--hdri_mode', action='store_true', help='HDRi conversion mode [lin_srgb -> acescg]')
args = parser.parse_args()





def getFiles(inPath):
	# get versions
	for r, d, f in os.walk(inPath):
		# print (r)
		# print (f)
		# print (f)
		break

	return f


def channelParse(channel_name):
	if channel_name != "":
		for i, i_val in enumerate(KNOWNCHANNELS):
			for lib, pipe_chan_name in KNOWNCHANNELS.items():
				if i_val == lib:
					for x in KNOWNCHANNELS:
						if channel_name in x:
							if channel_name in i_val:
								# print("channel name was {}, converted to {}".format(channel_name, pipe_chan_name))
								return pipe_chan_name
					if channel_name == pipe_chan_name:
						# print("channel_name is already {}".format(pipe_chan_name))					
						return pipe_chan_name


# def colorspaceParse(colorspace_name):
# 		if colorspace_name != "":
# 			for i, i_val in enumerate(KNOWNCOLORSPACES):
# 				for lib, pipe_color_name in KNOWNCOLORSPACES.items():
# 					if i_val == lib:
# 						for x in KNOWNCOLORSPACES:
# 							if colorspace_name in x:
# 								if colorspace_name in i_val:
# 									print("colorspace_name name was {}, converted to {}".format(colorspace_name, pipe_color_name))
# 									return pipe_color_name
# 						if colorspace_name == pipe_color_name:
# 							print("colorspace_name is already {}".format(pipe_color_name))					
# 							return pipe_color_name


def srgbParse(channel_name):
		if channel_name != "":
			if channelParse(channel_name) in KNOWNSRGBCHANNELS:
				# do srgb_texture - acescg conversion
				srgb_texture = True
			else:
				srgb_texture = False

			# print("convert to acescg from srgb_texture? : ", srgb_texture)

			return srgb_texture


def getUDIM(fileName):
	# file = fileName.replace(".","_")                      #deal with extention
	file = fileName.replace(" ","_")                        #remove spaces

	# split file extension from file and store to variables
	fn, ext = os.path.splitext(file)

	fileSplit = fn.split("_") # list of tokens
	# print(fileSplit)


	#get existing UDIM from file name
	for uDim in fileSplit:
		if str.isdigit(uDim) == True:                       
			if len(uDim) == 4:
				if int(uDim) >= 1001:
					# print ("UDIM detected : " + uDim)
					# fileRepo['dictUDIM'] = uDim
	
					return uDim

def getChannel(fileName):
	file = fileName.replace(" ","_").lower()                       #remove spaces

	# split file extension from file and store to variables
	fn, ext = os.path.splitext(file)
	# fn, ud = os.path.splitext(fn)


	fileSplit = fn.split("_") # list of tokens
	# print(fileSplit)

	#get existing channel from file name
	for channel_name in fileSplit:
		if channel_name != "":
			for i, i_val in enumerate(KNOWNCHANNELS):
				for lib, pipe_chan_name in KNOWNCHANNELS.items():
					if i_val == lib:
						for x in KNOWNCHANNELS:
							if channel_name in x:
								if channel_name in i_val:
									# print("channel name was {}, converted to {}".format(channel_name, pipe_chan_name))
									# print ("channel detected : " + pipe_chan_name)
									return pipe_chan_name
						if channel_name == pipe_chan_name:
							# print("channel_name is already {}".format(pipe_chan_name))
							# print ("channel detected : " + pipe_chan_name)
							return pipe_chan_name




def process(inPath, asset_name="", hdri=False, lin=False, out_srgb=False, raw=False, out=None):
	for tex in getFiles(inPath):
		print("*"*50)

		fn, ext = os.path.splitext(tex)	# split file extension from file and store to variables
		print("processing " + fn+ext)
		if "hdri" in fn:
			hdri = True

		if hdri == False:
			if asset_name != "":
				try:
					# NB: raw data channels are left alone
					if srgbParse(getChannel(tex)) == True:
						# default mode
						in_color="srgb_texture"
						out_color="acescg"

						if lin == True: 					# For lin_srgb color maps
							in_color = "lin_srgb"
						if out_srgb == True:				# For legacy srgb maps (display transform)
							in_color = "out_srgb"
						if raw == True:						# force raw mode (no transforms)
							in_color = "raw"
					else:
						in_color="raw"
						out_color="raw"
				except:
					print("no channel found, skipping color transform")
			else:
				print("Please enter asset name with -a [name]")



			if getUDIM(tex) == None:
				udim = "1001"
			else:
				udim = getUDIM(tex)

			
			try:
				## outFile = os.path.join(inPath, outFileName(asset_name, getChannel(tex), out_color, udim))
				if out == None:
					outFile = os.path.join(inPath, asset_name +"_tex_"+ getChannel(tex) +"_"+ out_color +"_"+ udim +".exr")
				else:
					outFile = os.path.join(out, asset_name +"_tex_"+ getChannel(tex) +"_"+ out_color +"_"+ udim +".exr")
				# print(outFile)
				subprocess.call(["maketx", PARMS, os.path.join(inPath,tex), "--colorconfig", COLORCONFIG, "--colorconvert", in_color, out_color, "-o", outFile])
			except:
				print("no channel found, skipping export")


		if hdri == True:
			in_color="lin_srgb"
			out_color="acescg"

			if out == None:
				## outFile = os.path.join(inPath, outFileName(fn, out_color))
				outFile = os.path.join(inPath, fn.lower() +"_hdri_"+ out_color +".exr")
			else:
				outFile = os.path.join(out, fn.lower() +"_hdri_"+ out_color +".exr")
			# print(outFile)

			if ext == '.hdr' or ext == '.exr':
				subprocess.call(["maketx", PARMS, os.path.join(inPath,tex), "--colorconfig", COLORCONFIG, "--colorconvert", in_color, out_color, "-o", outFile])
				hdri = False
			else:
				print("skipping non-hdri " + fn + ext)











process(SOURCEDIR, asset_name=args.asset_name, 
					hdri=args.hdri_mode, 
					lin=args.linear_mode,
					out_srgb=args.out_srgb,
					raw=args.raw,
					out=args.out_dir)
		





# TODO:
# spit texture to shots directory with versioning
# build maya file node texture updater to this path
# build tKinter GUI for texture_publish

# DONE:
# argparse cmd tool
```

**Comment by BigRoy** [comment]
Thanks for the detailed input, this is great.

I just wanted to say that I feel this isn't too much needed for Maya in particular at the time of publishing because Maya has a colorspace setting per file node and defines a rendering color space too. E.g. I've fixed that logic for maketx conversion in #4711 

I also don't think it's too relevant for for exports from #4294 Substance Painter because it only has color space settings per bit depth and not per output map.

Instead I do think it's relevant to those cases where a specific color space is undefined for input->output textures.

**Comment by jakubjezek001** [comment]
Recently I have seen this ACES central forum talking about similar issue and there were some suggestions you might be interested to read. Start from this comment and go down. https://community.acescentral.com/t/manual-editing-of-config-ocio/3524/24

Some of it can be reproduced with new OP colorspace distribution. Well not all of it, since we are still missing the loading capabilities.
